Repository VerifiedInc/one-click-signup-example-app, pull requests merged in 2024-11, with the labels that each got.

#8 docs: Comment the entire project
  README.md
  src/components/register/OtpStep.tsx
  src/components/register/SignupOneClickFormStep/index.tsx
  src/components/register/SimpleSignupFormStep/index.tsx
  src/components/register/SuccessfulSignUpStep.tsx
  src/pages/register/1-click/hosted.tsx
  src/pages/register/1-click/non-hosted.tsx
  src/pages/register/1-click/semi-hosted.tsx
  src/pages/register/index.tsx
  src/services/client/one-click-request-service.ts
  src/services/client/otp-request-service.ts
Labels: 10 min review

#9 feat: fix otp clear handling and remove unecessary condition
  src/components/register/OtpStep.tsx
  src/pages/register/1-click/non-hosted.tsx
  src/pages/register/1-click/semi-hosted.tsx
Labels: 1 min review

#10 feat: update based on feedback
  .env.example
  README.md
  src/components/register/OtpStep.tsx
  src/components/register/SignupOneClickFormStep/signup-one-click.schema.ts
  src/components/register/SimpleSignupFormStep/simple-signup.schema.ts
  src/pages/api/1-click/index.ts
  src/pages/register/1-click/hosted.tsx
  src/pages/register/1-click/non-hosted.tsx
  src/pages/register/1-click/semi-hosted.tsx
  src/pages/register/index.tsx
  src/types/OneClick.types.ts
  src/utils/api.ts
  src/utils/ssn.ts
Labels: 10 min review

#11 [Package] shared-ui referenced via github uri instead of npm package
  package-lock.json
  package.json
Labels: 1 min review

#12 chore: Uses shared-ui version from github
  package-lock.json
  package.json
Labels: hotfix, 1 min review

#13 updates the shared-ui version
  package-lock.json
  package.json
Labels: 1 min review

#14 Public registry
  next.config.mjs
  package-lock.json
  package.json
  src/components/layouts/main-layout/index.tsx
  src/components/register/DobFormStep/dob.schema.ts
  src/components/register/DobFormStep/index.tsx
  src/components/register/OtpStep.tsx
  src/components/register/PhoneStep.tsx
  src/components/register/ResendPhoneBanner.tsx
  src/components/register/SignupOneClickFormStep/index.tsx
  src/components/register/SignupOneClickFormStep/signup-one-click.schema.ts
  src/components/register/SimpleSignupFormStep/index.tsx
  src/components/register/SimpleSignupFormStep/simple-signup.schema.ts
  src/components/register/SuccessfulSignUpStep.tsx
  src/pages/register/1-click/hosted.tsx
  src/pages/register/1-click/non-hosted.tsx
  src/pages/register/1-click/semi-hosted.tsx
  src/pages/register/index.tsx
  src/styles/theme.ts
Labels: 5 min review

#15 chore: bump version and update imports
  package-lock.json
  package.json
  src/components/layouts/main-layout/index.tsx
  src/components/register/DobFormStep/dob.schema.ts
  src/components/register/DobFormStep/index.tsx
  src/components/register/OtpStep.tsx
  src/components/register/PhoneStep.tsx
  src/components/register/ResendPhoneBanner.tsx
  src/components/register/SignupOneClickFormStep/index.tsx
  src/components/register/SignupOneClickFormStep/signup-one-click.schema.ts
  src/components/register/SimpleSignupFormStep/index.tsx
  src/components/register/SimpleSignupFormStep/simple-signup.schema.ts
  src/components/register/SuccessfulSignUpStep.tsx
  src/pages/register/1-click/hosted.tsx
  src/pages/register/1-click/non-hosted.tsx
  src/pages/register/1-click/semi-hosted.tsx
  src/pages/register/index.tsx
  src/styles/theme.ts
Labels: hotfix, 5 min review

#16 feat: updated snackbar
  src/components/UI/Snackbar.tsx
  src/components/layouts/main-layout/MenuItem.tsx
  src/components/layouts/main-layout/index.tsx
  src/components/register/RedirectStep.tsx
  src/pages/register/1-click/hosted.tsx
  src/pages/register/1-click/non-hosted.tsx
  src/pages/register/1-click/semi-hosted.tsx
  src/pages/register/index.tsx
  src/services/client/otp-request-service.ts
Labels: 20 min review

#17 Update the example app with feedback changes
  .env.example
  README.md
  package-lock.json
  package.json
  src/components/UI/LegalLanguage.tsx
  src/components/UI/PageHeader.tsx
  src/components/UI/Snackbar.tsx
  src/components/UI/Title.tsx
  src/components/layouts/main-layout/index.tsx
  src/components/register/DobFormStep/index.tsx
  src/components/register/PhoneStep.tsx
  src/components/register/RedirectStep.tsx
  src/components/register/ResendPhoneBanner.tsx
  src/components/signup/DobFormStep/dob.schema.ts
  src/components/signup/DobFormStep/index.tsx
  src/components/signup/LegalLanguage.tsx
  src/components/signup/OtpStep.tsx
  src/components/signup/PhoneStep.tsx
  src/components/signup/RedirectStep.tsx
  src/components/signup/SignupOneClickFormStep/index.tsx
  src/components/signup/SignupOneClickFormStep/signup-one-click.schema.ts
  src/components/signup/SimpleSignupFormStep/index.tsx
  src/components/signup/SimpleSignupFormStep/simple-signup.schema.ts
  src/components/signup/SuccessfulSignUpStep.tsx
  src/pages/_app.tsx
  src/pages/_error.tsx
  src/pages/api/1-click/index.ts
  src/pages/api/create-otp.ts
  src/pages/api/verify-otp.ts
  src/pages/index.tsx
  src/pages/signup/1-click/hosted.tsx
  src/pages/signup/1-click/non-hosted.tsx
  src/pages/signup/1-click/semi-hosted.tsx
  src/pages/signup/index.tsx
  src/services/api/otp-sms-service.ts
  src/services/client/one-click-request-service.ts
  src/services/client/otp-request-service.ts
  src/types/OneClick.types.ts
  src/utils/1-click.ts
  src/utils/snackbar.tsx
  src/utils/ssn.ts
Labels: 30 min review

#18 fix: update logo reference in README.md
  README.md
Labels: 1 min review, single-line

#19 Improvements
  package-lock.json
  package.json
  src/components/signup/DobFormStep/index.tsx
  src/components/signup/OtpStep.tsx
  src/components/signup/PhoneStep.tsx
  src/components/signup/SignupOneClickFormStep/index.tsx
  src/hooks/useSteps.tsx
  src/pages/signup/1-click/non-hosted.tsx
  src/pages/signup/1-click/semi-hosted.tsx
  src/pages/signup/index.tsx
  src/services/client/one-click-request-service.ts
  src/utils/1-click.ts
Labels: 20 min review

#20 fixes one-click mismatch error cases and support single address
  .vscode/launch.json
  src/components/signup/DobFormStep/index.tsx
  src/components/signup/OtpStep.tsx
  src/components/signup/PhoneStep.tsx
  src/components/signup/SignupOneClickFormStep/index.tsx
  src/services/client/one-click-request-service.ts
  src/types/OneClick.types.ts
Labels: hotfix, 20 min review
